services:
  - type: web
    name: avika-api
    env: docker
    plan: free # Or your preferred plan, e.g., starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Set this in the Render dashboard
      - key: CHROMA_DB_PATH
        value: /var/data/chroma_storage # Path for the persistent disk
      - key: AVIKA_TITLES_PATH
        value: /app/Avika_Titles.docx
      - key: AVIKA_DOCS_PATH
        value: /app/Avika_Docs/
      - key: PYTHON_VERSION
        value: "3.10" # Or the specific version your `python:slim` resolves to, adjust if needed
    disk:
      name: chroma-data
      mountPath: /var/data/chroma_storage
      sizeGB: 1 # Smallest size, adjust if your DB grows
    autoDeploy: true # Optional: automatically deploy on pushes to main/master
    # healthCheckPath: /health # Optional: Render can use this
    # numInstances: 1 # Optional: default is 1
    # region: oregon # Optional: choose a region, e.g., oregon, frankfurt 